name: Build

on:
  release:
    types: [published]
  push:
    branches:
      - "master"
       
jobs:
  push_to_registries:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: write
      repository-projects: write
      packages: write 
    steps:    
    
      - name: add tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.gh_token }}
          tag_prefix: ""
          
                    
      - name: Check out the repo
        uses: actions/checkout@v2
        
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2 
        
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}       
          
                    
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./docker
          push: true
          tags: pavelogs/wordpress:${{ steps.tag_version.outputs.new_tag }}
          
                   

      - name: Create backup
        id: backup
        run: |
           mkdir ~/.ssh
           eval `ssh-agent -s`
           ssh-add - <<< "${{secrets.KEY}}" 
           ssh-keyscan -H ${{ secrets.PROXY_HOST }} >> ~/.ssh/known_hosts
           ssh ${{ secrets.USERNAME_HOST }}@${{ secrets.HOST_IP }} -o ProxyCommand="ssh -W %h:%p ${{ secrets.USERNAME_PROXY }}@${{ secrets.PROXY_HOST }}" -o StrictHostKeyChecking=no "mysqldump -u ${{ secrets.USERNAME_HOST }} ${{ secrets.DB }} > ./backup/${{ secrets.DB }}-${{ steps.tag_version.outputs.new_tag }}.sql"  
   
 
      - name: Slack Notification after backup
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: alert_project
          SLACK_COLOR: ${{ job.status }}
          SLACK_ICON: https://github.com/rtCamp.png?size=48
          SLACK_MESSAGE: 'Backup was successfully created'
          SLACK_TITLE: 'Backup DB'
          SLACK_USERNAME: Kostenko Pavel
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          
                                     
      - name: Helm Package and changes chart files
        run: |
          sed -i "s/^version:.*$/version: ${{ steps.tag_version.outputs.new_tag }}/" ./helm-source/wordpress/Chart.yaml
          sed -i "s/^appVersion:.*$/appVersion: ${{ steps.tag_version.outputs.new_tag }}/" ./helm-source/wordpress/Chart.yaml
          sed -i "s/tag:.*$/tag: ${{ steps.tag_version.outputs.new_tag }}/" ./helm-source/wordpress/values.yaml
          sed -i "s/targetRevision:.*$/targetRevision: ${{ steps.tag_version.outputs.new_tag }}/" ./app_argo.yaml
          cd ./helm-source
          helm package wordpress
          mv wp_project-${{ steps.tag_version.outputs.new_tag }}.tgz ../helm-releases
          cd ..
          helm repo index --url https://pavel167988.github.io/project_wp/ --merge index.yaml .                  
          
      - name: Push helm package
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add --all
          git commit -m "version app ${{ steps.tag_version.outputs.new_tag }}"
          git push
          
      - name: Slack Notification after push helm
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: alert_project
          SLACK_COLOR: ${{ job.status }}
          SLACK_ICON: https://avatars.githubusercontent.com/u/43742164?s=32&v=4
          SLACK_MESSAGE: 'Helm package was successfully packaged and uploaded to the repository'
          SLACK_TITLE: 'Job is done!'
          SLACK_USERNAME: Kostenko Pavel
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          
