name: Last commit
on:
  workflow_dispatch:
    inputs:
      rollback:
      description: 'Rollback'
      required: true
       
jobs:
  push_to_registries:
    name: Remove last commit
    runs-on: ubuntu-latest
    permissions:
      contents: write
      repository-projects: write
      packages: write 
    steps:             
                    
      - name: Check out the repo
        uses: actions/checkout@v2      
                
          

      - name: Commit changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git reset --hard HEAD^
          git add .
          git commit -m "Removed last commit"
          
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master     
          
